### ISSUE TITLE
Requesting to join the organization!

### ISSUE THREAD

**Issue by shubhamkarande** [PH-DC/support#11]
Please invite me to the GitHub Community Organization. 

- #### Name: Shubham Karande

- #### Discord Username(if exists): shubham_95
 https://discord.gg/8wDeYJ5y

- #### Additional Context:

I came to know about PHP-DC fron Chinmay Mulay
 I always wanted to learn new stuff & wanted to work with a group of people on a project

**Comment by Davekibh** [comment]
Add your name and discord Username!

**Comment by Davekibh** [comment]
### Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PHP-DC/people
