### ISSUE TITLE
Request to join the Organization ..

### ISSUE THREAD

**Issue by Sandeep0214** [PH-DC/support#13]
Please invite me to the GitHub Community Organization. 

- #### Name: Sandeep barik

- #### Discord Username(if exists): JellyBob#1215

- #### Additional Context: 
through our college group

 Yes

**Comment by Davekibh** [comment]
### Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PHP-DC/people
