### ISSUE TITLE
Request to join organization 

### ISSUE THREAD

**Issue by ptslegendplus** [PH-DC/support#16]
Please invite me to the GitHub Community Organization. 

- #### Name: PTS LEGEND PLUS 

- #### Discord Username(if exists): 
 ptslegendplus 

- #### Additional Context: Learning

**Comment by cmulay** [comment]
## Invitation sent for the GitHub Organisation. 
### Welcome to the community 🎉
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PHP-DC/people
