### ISSUE TITLE
Request to join

### ISSUE THREAD

**Issue by TechnicalHero17** [PH-DC/support#17]
Please invite me to the GitHub Community Organization. 

- #### Name: Technicalhero17-Design

- #### Discord Username(if exists): 
Technicalhero17-Design

- #### Additional Context:
My Friends

Learning

**Comment by cmulay** [comment]
## Invitation sent for the GitHub Organisation. 
### Welcome to the community 🎉
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/PHP-DC/people
