### ISSUE TITLE
Invite Me

### ISSUE THREAD

**Issue by AttentiveAryan** [PH-DC/support#18]
Please invite me to the GitHub Community Organization. 

- #### Name:

- #### Discord Username(if exists): 

- #### Additional Context:

**Comment by cmulay** [comment]
Hello @AttentiveAryan !
We are happy to see your interest in being part of the community but for now we are operating under head organization and it's sub organizations only. 
We will reopen this issue once we expand our boundaries.
Many Thanks,
@cmulay
